- hosts: ubuntu-test

  vars:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    ansible_become: yes
    ansible_become_method: sudo

  tasks:

    - name: get role path
      debug:
        msg: "{{ playbook_dir }}"


    - name: get task content
      cmd: 'ls -lR'
      register: content

    - name: print task content
      debug:
        msg: "{{ content }}"