- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  tasks:
    - name: query api
      uri:
        url: http://ubuntu-proxy:8081/repository/raw-api.github/repos/derailed/k9s/releases/latest
        return_content: true
        headers:
          X-API-Key: "{{portainer_token}}"
          Accept: "application/json"
        body_format: json
      register: api_response

#- name: parse api data
#  loop: "{{ api_response.json.assets }}"

    - name: print api content
      debug:
        msg: api_response