- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  pre_tasks:

    - name: preparing this repo as role
      block:

      - name: get repository name
        shell: 'cat .git/config|grep url|rev|cut -d "/" -f1|rev|cut -d "." -f1'
        register: repo_name

      - name: print config"
        debug:
          msg: "{{ repo_name.stdout }}"

      - name: preparing - collect role items
        find: 
          paths: "{{ playbook_dir }}"
          excludes: "roles"
          file_type: "directory"
        register: role_items

      - name: preparing - create playbook role dir
        file:
          path: "/tmp/semaphore/.ansible/roles/{{ role_name.stdout }}"
          state: directory

      - name: preparing - symlink project items as role
        file:
          src: "{{ item }}"
          dest: "/tmp/semaphore/.ansible/roles/{{ role_name.stdout }}/{{ item | basename}}"
          state: link
        with_items: "{{ role_items.files | map(attribute='path') | list }}"

      delegate_to: localhost

    - name: adding private repositories
      block:
      
        - name: hardening os
          git:
            repo: "https://{{github_token_default}}@github.com/peedy2495/ansible-hardening-addition.git"
            dest: "/tmp/semaphore/.ansible/roles/hardening"
            version: main
      
      delegate_to: localhost