- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    registries: "{{ lookup('file', 'vars/test.json') | from_json['registries'] }}"

    result: "{{ registries | json_query(_query) }}"
    _query: '[].[image]|[]'

  tasks:
    - name: testing
      debug:
        msg: "{{ result }}"