- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    containers: "{{ lookup('file', 'vars/test.json') | from_json }}"

  tasks:

    - set_fact:
        registries: "{{ containers | json_query('[].registry') }}"

    - name: testing
      debug:
        msg: "{{ containers | json_query('[?registry=={{ item }}].images[].image') }}"
      loop: "{{ registries }}"