- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    github_proxy_port: "8081"
    github_proxy_proto: "http"
    github_proxy_ip: "192.168.123.180"
    github_proxy_path: "/repository/raw-github"
    github_proxy_api_path: "/repository/raw-api.github"

  tasks:
    - name: import credentials
      include_vars: creds.yml
      no_log: true

    - name: query api
      uri:
        url: "{{github_proxy_proto}}://{{github_proxy_ip}}:{{github_proxy_port}}{{github_proxy_api_path}}/repos/derailed/k9s/releases/latest"
        # url: http://192.168.123.180:8081/repository/raw-api.github/repos/derailed/k9s/releases/latest
        validate_certs: false
        return_content: true
        headers:
          X-API-Key: "{{portainer_token}}"
        body_format: json
      register: api

    - name: convert to json
      set_fact:
        api_json: "{{ api.content | from_json }}"

    - name: kubernetes - install k9s - pull package
      loop: "{{ api_json.assets }}"
      loop_control:
        label: "{{ item.name }}"
      apt:
        deb: '{{github_proxy_proto}}://{{github_proxy_ip}}:{{github_proxy_port}}{{github_proxy_path}}{{ item.browser_download_url | urlsplit("path") }}'
      when: "'k9s_linux_amd64.deb' in item.name"