- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  tasks:
    - name: import credentials
      include_vars: creds.yml
      no_log: true

    - name: query api
      uri:
        url: http://192.168.123.180:8081/repository/raw-api.github/repos/derailed/k9s/releases/latest
        validate_certs: false
        return_content: true
        headers:
          X-API-Key: "{{portainer_token}}"
        body_format: json
      register: api_response

  as_json: "{{ api_response.stdout }} | from_json"

#- name: parse api data
#  loop: "{{ api_response.json.assets }}"

    - name: print api content
      debug:
        msg: "{{ as_json }}"