- hosts: all
  gather_facts: true
  vars:
    ansible_become: yes
    ansible_become_method: sudo
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
    role_name: "{{ playbook_dir | basename }}"

  pre_tasks:

    - name: preparing local environment
      block:

      - name: preparing - create playbook role dir
        file:
          path: "/tmp/semaphore/.ansible/roles/{{ role_name }}"
          state: directory

      - name: preparing - collect role items
        find: 
          paths: "{{ playbook_dir }}"
          excludes: "roles"
          file_type: "directory"
        register: role_items

      - name: preparing - symlink project items as role
        file:
          src: "{{ item }}"
          dest: "/tmp/semaphore/.ansible/roles/{{ role_name }}/{{ item | basename}}"
          state: link
        with_items: "{{ role_items.files | map(attribute='path') | list }}"

      delegate_to: localhost
      vars:
        ansible_become: false

    - name: adding private repositories
      block:
      
        - name: hardening os
          git:
            repo: "https://{{github_token_default}}@github.com/peedy2495/ansible-hardening-addition.git"
            dest: "{{ playbook_dir }}/roles/hardening"
            version: main
      
      delegate_to: localhost
      vars:
        ansible_become: false


  # roles:
  #   - "{{ role_name }}"