- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    images: "{{ lookup('file', 'vars/test.json') }}"

  tasks:

  - name: "Print all hostnames"
    debug:
      msg: "{{ item.registry }}"
    loop: "{{ images }}"
    loop_control:
      label: "registry: {{ item.registry }}"