- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    content: "{{ lookup('file', 'vars/test.json') | from_json }}"

  tasks:

    - set_fact:
       registries: "{{ content | json_query('[].registry[*]') }}"

    - debug:
        msg: "{{ lookup('ansible.utils.to_paths', item) }}"
      loop: "{{ registries }}"
      loop_control:
        loop_var: item
      vars:
        _query: '[?registry==`{{ item }}`].[registry, images[].image]'

    - debug:
        msg: "{{ lookup('ansible.utils.to_paths', content) }}"