- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    content: "{{ lookup('file', 'vars/test.json') | from_json }}"

  tasks:

    #- set_fact:
    #    registries: "{{ content | json_query('[].registry') }}"
#
    #- debug:
    #    msg: "{{ content | json_query(_query) }} }}"
    #  loop: "{{ registries }}"
    #  loop_control:
    #    loop_var: item
    #  vars:
    #    _query: '[?registry==`{{ item }}`].[registry, images[].image]'

    - name: Print registry and image information separately
      debug:
        msg: "Registry: {{ item.registry }}, Image: {{ item.image }}"
      loop: "{{ content }}"
      loop_control:
        label: "{{ item.registry }}"
      vars:
        images_with_registry: "{{ item.images | map('combine', {'registry': item.registry}) | list }}"
      loop: "{{ images_with_registry }}"  