- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  tasks:
    - name: import credentials
      include_vars: creds.yml
      no_log: true

    - name: Create Nexus3 "testing" Apt proxy repository
      uri:
        url: "http://192.168.123.180:8081/service/rest/v1/repositories/apt/proxy"
        force_basic_auth: yes
        user: "admin"
        password: "{{ nexus_credentials }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
           "name": "testing",
           "online": true,
           "storage": {
             "blobStoreName": "default",
             "strictContentTypeValidation": true
           },
           "apt": {
             "distribution": "xenial",
             "flat": true
           },
           "proxy": {
             "remoteUrl": "http://archive.ubuntu.com/ubuntu/"
           },
           "negativeCache": true,
           "contentMaxAge": -1,
           "metadataMaxAge": -1,
           "httpClient": {
             "blocked": false,
             "autoBlock": true,
             "connection": {
               "retries": 0,
               "userAgentSuffix": "MySuffix"
             },
             "authentication": {
               "ntlm": {
                 "enabled": false
               },
               "bearerToken": {
                 "enabled": false
               },
               "username": "myUsername",
               "password": "myPassword"
             },
             "proxy": {
               "httpProxy": "myHttpProxy",
               "httpsProxy": "myHttpsProxy",
               "blocked": false
             },
             "timeout": 1,
             "blocked": false
           }
          }
        body_format: json
      register: repo_creation_result

    - debug:
        var: repo_creation_result