- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    json_content: "{{ lookup('file', 'vars/test.json') }}"

  tasks:

    - name: Extract registry and image names
      debug:
        msg: "{{ item.registry }}/ {{ image.image }}"
      loop: "{{ json_content }}"
      loop_control:
        loop_var: item
      with_items: "{{ item.images }}"
      loop_control:
        loop_var: image