- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    content: "{{ lookup('file', 'files/test.json') | from_json }}"
  vars_files:
    - containers.yml

  tasks:
    - name: Print registry and image information separately
      debug:
        msg: "Registry: {{ item.0.registry.name }} @{{ item.0.registry.proxyport }}, Image: {{ item.1 }}"
      with_subelements:
        - "{{ content }}"
        - images

    - debug:
        msg: "{{ proxyPorts.dockerhub }}"