- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    registries: "{{ lookup('file', 'vars/test.json') | from_json['registries'] }}"

  tasks:
    - name: Print registry URLs and image names
      debug:
        msg: "Registry URL: {{ item.url }}, Image Name: {{ item.image }}"
      loop: "{{ registries | json_query('[].{url: url, image: images[]}') }}"