- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    registries: "{{ lookup('file', 'vars/test.json') }}"

  tasks:
    - name: Print registry URLs and image names
      debug:
        msg: "Registry URL: {{ item.url }}, Image Name: {{ image }}"
      loop: "{{ registries.registries }}"
      loop_control:
        loop_var: registry
      vars:
        registry_url: "{{ registry.url }}"
      with_items: "{{ registry.images }}"
      loop_control:
        loop_var: image