- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  tasks:
    - name: import credentials
      include_vars: creds.yml
      no_log: true

    - name: Create Nexus3 "testing" Apt proxy repository
      uri:
        url: "http://192.168.123.180:8081/service/rest/v1/repositories/apt/proxy"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Basic base64({{ nexus_credentials }})"
        body: |
          {
            "name": "testing",
            "online": true,
            "storage": {
              "blobStoreName": "default",
              "strictContentTypeValidation": true
            },
            "apt": {
              "distribution": "xenial",
              "flat": true
            },
            "proxy": {
              "remoteUrl": "http://archive.ubuntu.com/ubuntu/"
            }
          }
        body_format: json
      register: repo_creation_result

    - debug:
        var: repo_creation_result