- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    containers: "{{ lookup('file', 'vars/test.json') | from_json }}"

  tasks:

    - set_fact:
        registries: "{{ containers | json_query('[].registry') }}"

    - name: testing
      debug:
        msg: "{{ item }} :: {{ containers | json_query(_query) | flatten}}"
      loop: "{{ registries }}"
      vars:
        _query: '[?registry==`{{ item }}`].images[].image'