- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    content: "{{ lookup('file', 'vars/test.json') | from_json }}"

  tasks:

    - set_fact:
       registries: "{{ content | json_query('[].registry') }}"

    - debug:
        msg: "{{ content | json_query(_query) }} }}"
      loop: "{{ registries }}"
      loop_control:
        loop_var: item
      vars:
        _query: '[?registry==`{{ item }}`].[registry, images[].image]'

    - debug:
        msg: "xx:{{item.registry}} yy:{{ lookup('ansible.utils.to_paths', item) | json_query(_query) | json_query(_q2) }}"
      loop: "{{ lookup('ansible.utils.to_paths', item) | json_query(_query) | json_query(_q2) }}"
      with_items:
        - "{{ content }}"
      vars:
        _query: '*'
        _q2: '[1:]'

    - name: Demonstrate nested loops
      debug:
        msg: "Outer item={{ outer_item }} Inner item={{ inner_item }}"
      loop: "{{ outer_list }}"
      vars:
        outer_item: "{{ item }}"
        inner_list: ["one", "two", "three"]
        inner_item: "{{ inner_list }}"