- hosts: localhost
  gather_facts: true
  vars:
    ansible_become: false
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
    role_name: "native"

  pre_tasks:

    - name: get repository name
      command: "cat .git/config"
      register: config

    - name: print config"
      debug:
        msg: "{{ config.stdout_lines }}"

    - name: preparing - collect role items
      find: 
        paths: "{{ playbook_dir }}"
        excludes: "roles"
        file_type: "directory"
      register: role_items

    - name: preparing - create playbook role dir
      file:
        path: "/tmp/semaphore/.ansible/roles/{{ role_name }}"
        state: directory

    - name: preparing - symlink project items as role
      file:
        src: "{{ item }}"
        dest: "/tmp/semaphore/.ansible/roles/{{ role_name }}/{{ item | basename}}"
        state: link
      with_items: "{{ role_items.files | map(attribute='path') | list }}"

    - name: hardening os
      git:
        repo: "https://{{github_token_default}}@github.com/peedy2495/ansible-hardening-addition.git"
        dest: "/tmp/semaphore/.ansible/roles/hardening"
        version: main