# this playbook is for deploying a complete ubuntu desktop environment

- hosts: ubuntu-test
  gather_facts: true
  vars:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    ansible_become: yes
    ansible_become_method: sudo
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
    role_name: "{{ playbook_dir | basename }}"

  pre_tasks:

  - name: get user
    command: "ip addr"
    register: whoami
    delegate_to: localhost
    vars:
      ansible_become: false

  - name: testing
    debug:
      msg: "{{ whoami }}"
    
  #roles:
  #  - "{{ role_name }}"