- hosts: all
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

    json_content: "{{ lookup('file', 'vars/test.json') }}"

  tasks:
    - name: Extract registry and image names
      debug:
        msg: "{{ item.0.registry }}/ {{ item.1.image }}"
      loop: "{{ json_content | map(attribute='registry') | product(json_content | map(attribute='images')) | list }}"
      loop_control:
        loop_var: item