- hosts: all
  gather_facts: true
  vars:
    ansible_become: yes
    ansible_become_method: sudo
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
    role_name: "native"

  roles:
    - "{{ role_name }}"