- hosts: ubuntu-test
  gather_facts: true
  vars:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    ansible_become: no
    ansible_become_method: sudo
    role_name: testing

  pre_tasks:

    - name: preparing - turn privilege escalation off for next task, only
      set_fact:
        ansible_become: no

    - name: preparing - get current role name
      shell: 'cat /tmp/semaphore/repository_2_2/.git/config|grep url|rev|cut -d "/" -f1|rev|cut -d "." -f1'
      register: curr_role_name
      delegate_to: localhost

    - name: preparing - propagate role_name
      set_fact:
        role_name: "{{ curr_role_name.stdout }}"

    - name: preparing - turn privilege escalation off for next task, only
      set_fact:
        ansible_become: no

    - name: preparing - create playbook role dir
      file:
        path: "{{ playbook_dir }}/roles/{{ curr_role_name.stdout }}"
        state: directory
      delegate_to: localhost
      become: no

    - name: preparing - turn privilege escalation off for next task, only
      set_fact:
        ansible_become: no

    - name: preparing - collect role items
      find: 
        paths: "{{ playbook_dir }}"
        excludes: "roles"
        file_type: "directory"
      register: role_items 
      delegate_to: localhost

    - name: preparing - turn privilege escalation off for next task, only
      set_fact:
        ansible_become: no

    - name: preparing - symlink project items as role
      file:
        src: "{{ item }}"
        dest: "{{ playbook_dir }}/roles/{{ role_name }}/{{ item | basename}}"
        state: link
      with_items: "{{ role_items.files | map(attribute='path') | list }}"
      delegate_to: localhost
    
  roles:
    - "{{ role_name }}"