- hosts: ubuntu-test
  vars:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    ansible_become: no
    ansible_become_method: sudo

  tasks:

    - name: get current role name
      shell: 'cat /tmp/semaphore/repository_2_2/.git/config|grep url|rev|cut -d "/" -f1|rev|cut -d "." -f1'
      register: curr_role_name
      delegate_to: localhost

    - name: print role name
      debug:
        msg: "{{ curr_role_name }}"

    - name: create playbook role dir
      delegate_to: localhost
      file:
        path: "{{ playbook_dir }}/roles/{{ curr_role_name.stdout_lines }}"
        state: directory
        