- hosts: ubuntu-test
  vars:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    ansible_become: yes
    ansible_become_method: sudo

  pre_tasks:
    - name: preparing - turn privilege escalation off
      set_fact:
        ansible_become: no

    - name: preparing - get current role name
      shell: 'cat /tmp/semaphore/repository_2_2/.git/config|grep url|rev|cut -d "/" -f1|rev|cut -d "." -f1'
      register: curr_role_name
      delegate_to: localhost

    - name: create playbook role dir
      file:
        path: "{{ playbook_dir }}/roles/{{ curr_role_name.stdout }}"
        state: directory
      delegate_to: localhost
      become: no

    - name: collect role items
      find: 
        paths: "{{ playbook_dir }}"
        excludes: "roles"
        #file_type: "directory"
      register: role_items 
      delegate_to: localhost

    - name: symlink project items as role
      file:
        src: "{{ item }}"
        dest: "{{ playbook_dir }}/roles/{{ curr_role_name.stdout }}/{{ item | basename}}"
        state: link
      with_items: "{{ role_items.files | map(attribute='path') | list }}"
      delegate_to: localhost