- hosts: ALL
  vars:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    ansible_become: no
    ansible_become_method: sudo

  tasks:

    - name: create playbook role dir
      delegate_to: localhost
      file:
        path: "{{ playbook_dir }}/roles/{{ role }}"
        state: directory

    - name: get current role name
      delegate_to: localhost
      command: 'cat /tmp/semaphore/repository_2_2/.git/config|grep url|rev|cut -d '/' -f1|rev|cut -d '.' -f1'
      register: curr_role_name

    - name: print role name
      debug:
        msg: "{{ role_name }}"

        